# Generated by Django 6.0.4 on 2026-04-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover_image_url',
            new_name='thumbnail',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='Book_isbn_382798_idx',
            old_name='BookstoreAp_isbn_fd0790_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='Book_status_3f9e04_idx',
            old_name='BookstoreAp_status_216c6f_idx',
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
