# Generated by Django 6.0.4 on 2026-04-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='Book_order_order_n_f96f05_idx',
            old_name='BookstoreAp_order_n_84224a_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='Book_order_custome_f33802_idx',
            old_name='BookstoreAp_custome_1e3bfc_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='Book_order_status_149274_idx',
            old_name='BookstoreAp_status_50b145_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='Book_review_book_id_4f07b2_idx',
            old_name='BookstoreAp_book_id_b6d524_idx',
        ),
    ]
