# Generated by Django 6.0.4 on 2026-05-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book_author',
        ),
    ]
